import assert from 'node:assert/strict';
import { execFileSync, spawn } from 'node:child_process';
const url = process.env.MILL_TEST_DATABASE_URL;
if (!url) throw new Error('Set MILL_TEST_DATABASE_URL to the disposable test database.');
const parsed = new URL(url);
if (!['127.0.0.1','localhost'].includes(parsed.hostname) || !parsed.pathname.startsWith('/mill_test')) throw new Error('Concurrency tests only run against a local mill_test database.');
const bin = process.env.PSQL_BIN || 'psql';
const args = [url,'-X','-q','-t','-A','-v','ON_ERROR_STOP=1'];
const sync = sql => execFileSync(bin,args,{input:sql,encoding:'utf8'}).trim();
const run = sql => new Promise(resolve => {
  const child=spawn(bin,args,{windowsHide:true});let out='',err='';
  child.stdout.on('data',d=>out+=d);child.stderr.on('data',d=>err+=d);
  child.on('close',code=>resolve({code,out:out.trim(),err}));child.stdin.end(sql);
});
const auth="set role authenticated; set request.jwt.claim.sub='11111111-1111-4111-8111-111111111111';";
sync("insert into public.mill_staff values ('11111111-1111-4111-8111-111111111111',true) on conflict do nothing;");
const supplier=sync(`${auth} select public.mill_post('party','{"kind":"supplier","name":"Race supplier"}',gen_random_uuid());`);
const customer=sync(`${auth} select public.mill_post('party','{"kind":"customer","name":"Race customer"}',gen_random_uuid());`);
sync(`${auth} select public.mill_post('purchase','{"party_id":"${supplier}","date":"2026-09-20","raw_type_id":2,"weight":200,"unit_price":50}',gen_random_uuid());
select public.mill_post('processing','{"date":"2026-09-20","raw_type_id":2,"input_weight":200,"outputs":[{"product_id":21,"weight":150},{"product_id":22,"weight":0},{"product_id":23,"weight":0},{"product_id":24,"weight":0}]}',gen_random_uuid());`);
const saleSql=`begin; ${auth} select public.mill_post('sale','{"party_id":"${customer}","date":"2026-09-20","product_id":21,"weight":100,"unit_price":10}',gen_random_uuid()); select pg_sleep(0.3); commit;`;
let results=await Promise.all([run(saleSql),run(saleSql)]);
assert.equal(results.filter(r=>r.code===0).length,1,'Only one concurrent sale can consume the remaining stock');
assert.equal(sync(`${auth} select available from public.mill_product_stock where id=21;`),'50.000');
const sale=sync(`${auth} select id from public.mill_entries where party_id='${customer}' and kind='sale';`);
const paymentSql=`begin; ${auth} select public.mill_post('payment','{"target_id":"${sale}","date":"2026-09-20","amount":600}',gen_random_uuid()); select pg_sleep(0.3); commit;`;
results=await Promise.all([run(paymentSql),run(paymentSql)]);
assert.equal(results.filter(r=>r.code===0).length,1,'Concurrent payments cannot overpay');
const deliverySql=`begin; ${auth} select public.mill_post('delivery','{"target_id":"${sale}","date":"2026-09-20","weight":60}',gen_random_uuid()); select pg_sleep(0.3); commit;`;
results=await Promise.all([run(deliverySql),run(deliverySql)]);
assert.equal(results.filter(r=>r.code===0).length,1,'Concurrent deliveries cannot overdeliver');
const id=crypto.randomUUID();
const retrySql=`${auth} select public.mill_post('sale','{"party_id":"${customer}","date":"2026-09-20","product_id":21,"weight":20,"unit_price":10}','${id}');`;
results=await Promise.all([run(retrySql),run(retrySql)]);
assert.ok(results.every(r=>r.code===0),'Both idempotent retries return successfully');
assert.equal(results[0].out,results[1].out,'Same request returns same entry');
assert.equal(sync(`${auth} select available from public.mill_product_stock where id=21;`),'30.000');
console.log('PASS: concurrent sales, payments, deliveries, and idempotent retries.');
