-- Test only, disposable database after migrations 001–005. Rolls back all fixtures.
begin;
insert into public.mill_staff(user_id) values ('11111111-1111-4111-8111-111111111111') on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claim.sub','11111111-1111-4111-8111-111111111111',true);
do $$
declare supplier uuid; customer uuid; purchase uuid; process uuid; sale uuid; delivery uuid; request uuid:=gen_random_uuid(); payload jsonb; rejected boolean; n bigint;
begin
  supplier:=public.mill_post('party','{"kind":"supplier","name":"Supplier test","father_name":"Father test"}',gen_random_uuid());
  customer:=public.mill_post('party','{"kind":"customer","name":"Customer test"}',gen_random_uuid());
  assert (select father_name='Father test' from public.mill_party_balances where id=supplier),'father name returned in accounts';
  purchase:=public.mill_post('purchase',jsonb_build_object('party_id',supplier,'date','2026-09-20','raw_type_id',1,'weight',1000,'unit_price',50,'logistics',1000,'paid',10000,'payment_method','cheque','cheque_number','CH-001','payment_institution','Sarafi test'),gen_random_uuid());
  assert (select remaining=40000 from public.mill_invoice_balances where id=purchase),'cheque counts as paid immediately';
  assert (select payment_method='cheque' and cheque_number='CH-001' and payment_institution='Sarafi test' from public.mill_payments where target_id=purchase),'initial cheque details saved';
  assert (select sum(amount)=0 from public.mill_expense_report),'purchase logistics excluded from expenses';
  assert (select value=51000 from public.mill_raw_stock where id=1),'transport still in raw inventory cost';
  assert (select payments->0->>'cheque_number'='CH-001' from public.mill_ledger where id=purchase),'purchase details include cheque';
  process:=public.mill_post('processing_start','{"date":"2026-09-20","raw_type_id":1,"input_weight":600,"notes":"Machine one"}',gen_random_uuid());
  assert (select quantity=400 and in_process=600 and value=20400 from public.mill_raw_stock where id=1),'start reserves rice and snapshots cost';
  assert (public.mill_snapshot()->'summary'->>'processing_count')::integer=0,'ongoing not counted as completed';
  assert (public.mill_snapshot()->'summary'->>'wastage')::numeric=0,'ongoing rice is not waste';
  assert jsonb_array_length(public.mill_snapshot()->'ongoing_processes')=1,'ongoing page data';
  assert (select raw_type_id=1 and processing_status='ongoing' from public.mill_ledger where id=process),'ongoing record has rice type';
  rejected:=false; begin perform public.mill_post('processing_start','{"date":"2026-09-20","raw_type_id":1,"input_weight":500}',gen_random_uuid()); exception when others then rejected:=true; end;
  assert rejected,'cannot reuse reserved rice';
  payload:=jsonb_build_object('id',process,'date','2026-09-21','notes','Completed shift','outputs','[{"product_id":11,"weight":245,"bag_size":24.5,"bag_mark":"Talha"},{"product_id":12,"weight":70,"bag_size":70,"bag_mark":"Mahfooz"},{"product_id":12,"weight":70,"bag_size":70,"bag_mark":"Talha"},{"product_id":13,"weight":100,"bag_size":20,"bag_mark":"Talha"},{"product_id":14,"weight":15}]'::jsonb);
  assert public.mill_post('processing_complete',payload,request)=process;
  assert public.mill_post('processing_complete',payload,request)=process,'completion retry idempotent';
  assert (select completed_date='2026-09-21' and completed_date_solar_hijri='1405-06-30' and expenses=0 from public.mill_batches where entry_id=process),'completion date and zero process expenses';
  assert (select quantity=400 and in_process=0 from public.mill_raw_stock where id=1),'completion does not deduct raw twice';
  assert (select available=245 from public.mill_packaged_stock where product_id=11 and bag_size=24.5 and bag_mark='Talha'),'packaged output';
  assert (public.mill_snapshot()->'summary'->>'wastage')::numeric=100,'loss computed only at completion';
  rejected:=false; begin perform public.mill_post('processing_complete',payload,gen_random_uuid()); exception when others then rejected:=true; end;
  assert rejected,'second completion with different request rejected';
  rejected:=false; begin perform public.mill_post('sale',jsonb_build_object('date','2026-09-21','party_id',customer,'product_id',11,'bag_size',24.5,'bag_mark','Mahfooz','weight',24.5,'unit_price',100),gen_random_uuid()); exception when others then rejected:=true; end;
  assert rejected,'cannot sell other mark despite total product stock';
  sale:=public.mill_post('sale',jsonb_build_object('date','2026-09-21','party_id',customer,'product_id',11,'bag_size',24.5,'bag_mark','Talha','weight',49,'unit_price',100,'delivered',24.5),gen_random_uuid());
  assert (select available=196 and physical=220.5 and reserved=24.5 from public.mill_packaged_stock where product_id=11 and bag_size=24.5 and bag_mark='Talha'),'sale and initial delivery preserve package stock';
  delivery:=public.mill_post('delivery',jsonb_build_object('date','2026-09-22','target_id',sale,'weight',24.5),gen_random_uuid());
  assert (select bag_size=24.5 and bag_mark='Talha' from public.mill_ledger where id=delivery),'delivery inherits packaging';
  perform public.mill_post('void',jsonb_build_object('id',delivery,'reason','test'),gen_random_uuid());
  assert (select physical=220.5 and reserved=24.5 from public.mill_packaged_stock where product_id=11 and bag_size=24.5 and bag_mark='Talha'),'delivery reversal restores same package stock';
  select count(*) into n from public.mill_entries;
  rejected:=false; begin perform public.mill_post('payment',jsonb_build_object('date','2026-09-22','target_id',purchase,'amount',100,'payment_method','cheque'),gen_random_uuid()); exception when others then rejected:=true; end;
  assert rejected and (select count(*)=n from public.mill_entries),'missing cheque number rolls back payment';
  perform public.mill_post('payment',jsonb_build_object('date','2026-09-22','target_id',purchase,'amount',100,'payment_method','cheque','cheque_number','CH-002','payment_institution','Bank test'),gen_random_uuid());
  assert (select remaining=39900 from public.mill_invoice_balances where id=purchase),'later cheque settles payable';
  process:=public.mill_post('processing_start','{"date":"2026-09-22","raw_type_id":1,"input_weight":100}',gen_random_uuid());
  perform public.mill_post('void',jsonb_build_object('id',process,'reason','cancelled'),gen_random_uuid());
  assert (select quantity=400 and in_process=0 from public.mill_raw_stock where id=1),'cancelling start releases rice';
  raise notice 'PASS: father name, cheques, purchase-only logistics, start/complete/reservation, packaged sales/delivery/reversal, completion idempotency.';
end $$;
rollback;
