import { createContext, useContext, useEffect, useMemo, useState } from 'react';

const STORAGE_KEY = 'rice-factory-language';
const defaultLanguage = 'fa-AF';

const english = {
  'صفحهٔ اصلی': 'Overview', 'خرید برنج خام': 'Raw rice purchases', 'تأمین‌کنندگان': 'Suppliers',
  'پروسس برنج': 'Rice processing', 'پروسس امانتی': 'Contract processing', 'موجودی گدام': 'Inventory',
  'فروش و تحویل': 'Sales and delivery', 'مشتریان': 'Customers', 'مصارف': 'Expenses', 'حساب من': 'My account',
  'بخش‌های کارخانه': 'Factory sections', 'فهرست اصلی': 'Main navigation', 'کیفیت در هر مرحله.': 'Quality at every step.',
  'دقت در هر دانه.': 'Precision in every grain.', 'خروج': 'Sign out', 'در حال خروج…': 'Signing out…',
  'کارخانه': 'Factory', 'مدیریت کارخانه': 'Factory management', 'سیستم مدیریت کارخانه': 'Factory management system',
  'واحد پول: افغانی · وزن: کیلوگرام · تاریخ ثبت: میلادی': 'Currency: Afghan afghani · Weight: kilograms · Record date: Gregorian',
  'تازه‌سازی اطلاعات': 'Refresh data', 'در حال تازه‌سازی…': 'Refreshing…', 'در حال دریافت اطلاعات کارخانه…': 'Loading factory data…',
  'اگر راه‌اندازی تازه است، مدیر باید مهاجرت‌های دیتابیس را اجرا کند و دسترسی کارمند را فعال سازد. در صورت وجود اطلاعات قبلی، ممکن است نمایش آن تازه نباشد.': 'If this is a new setup, an administrator must run the database migrations and enable staff access. Existing data may take a moment to appear.',
  'ثبت خرید': 'Record purchase', 'ثبت پروسس': 'Record processing', 'ثبت فروش': 'Record sale', 'نمای کلی فعالیت‌های کارخانه': 'Factory activity overview',
  'خوش آمدید، {name}.': 'Welcome, {name}.', 'وضعیت موجودی، حساب‌ها و فعالیت‌های کارخانه در یک نگاه.': 'Inventory, accounts, and factory activity at a glance.',
  'نمایش زبان انگلیسی': 'Switch to English', 'نمایش زبان دری': 'Switch to Dari', 'English': 'English', 'دری': 'Dari', 'باز و بسته کردن فهرست': 'Toggle navigation', 'واردشده با نام': 'Signed in as', 'باقی': 'remaining',
  'صفحهٔ اصلی کارخانهٔ برنج': 'Rice factory home', 'کارخانهٔ برنج': 'Rice Factory', 'از دانه تا شکوفایی': 'From grain to growth',
  'کارهای خوب\nآغاز می‌شوند با\nیک دانهٔ برنج.': 'Good work\nbegins with\na single grain.',
  'فضای اختصاصی برای مدیریت خرید، پروسس، فروش و حساب‌های کارخانهٔ شما.': 'A dedicated space for managing your factory purchases, processing, sales, and accounts.',
  'ریشه در کیفیت.': 'Rooted in quality.', 'آماده برای هر روز.': 'Ready for every day.', 'ورود کارمندان': 'Staff sign in',
  'مدیریت یک‌جای کارهای روزانه': 'Manage daily operations in one place', 'خوش آمدید.': 'Welcome.', 'به حساب کارخانهٔ برنج وارد شوید.': 'Sign in to your rice factory account.',
  'اتصال سیستم هنوز تنظیم نشده است. برای تکمیل راه‌اندازی با مدیر سیستم تماس بگیرید.': 'The system connection is not configured yet. Contact your administrator to complete setup.',
  'آدرس ایمیل': 'Email address', 'رمز عبور': 'Password', 'رمز عبور را وارد کنید': 'Enter your password', 'نمایش': 'Show', 'پنهان': 'Hide',
  'ایمیل معتبر و رمز عبور را وارد کنید.': 'Enter a valid email and password.', 'در حال ورود…': 'Signing in…', 'ورود': 'Sign in',
  'برای حساب یا رمز عبور کمک می‌خواهید؟': 'Need help with your account or password?', 'با مدیر کارخانه تماس بگیرید.': 'Contact the factory administrator.',
  'دقت در هر دانه.': 'Precision in every grain.', 'در حال آماده‌سازی حساب…': 'Preparing your account…', 'ثبت نشده': 'Not provided', 'موجود نیست': 'Unavailable',
  'مشخصات حساب کاربری': 'Account details', 'مشخصات حسابی که با آن وارد شده‌اید.': 'Details for the account you are signed in with.', 'برای تغییر مشخصات یا کمک در رمز عبور، با مدیر کارخانه تماس بگیرید.': 'Contact the factory administrator to change your details or get password help.',
  'آدرس ایمیل': 'Email address', 'تاریخ ایجاد حساب': 'Account created',
  'مواد اولیهٔ کارخانه': 'Factory raw materials', 'سابقهٔ خریدها': 'Purchase history', 'سابقهٔ پرداخت‌های نقدی': 'Cash payment history',
  'هنوز موردی ثبت نشده است.': 'Nothing has been recorded yet.', 'انتخاب کنید': 'Select', 'جستجو…': 'Search…', 'موردی پیدا نشد.': 'No matches found.', 'جستجو در': 'Search in',
  'بستن': 'Close', 'جزئیات': 'Details', 'پرداخت': 'Payment', 'تحویل': 'Delivery', 'ابطال': 'Void', 'انصراف': 'Cancel', 'ذخیره': 'Save', 'ویرایش': 'Edit',
  'تأیید و ثبت': 'Confirm and save', 'در حال ثبت…': 'Saving…', 'کوشش دوباره': 'Try again', 'قبلی': 'Previous', 'بعدی': 'Next',
  'دریافت اطلاعات ممکن نشد.': 'Could not load the information.', 'لطفاً منتظر بمانید…': 'Please wait…', 'سندی با این مشخصات پیدا نشد.': 'No matching record was found.',
  'حساب‌ها و سابقهٔ معاملات': 'Accounts and transaction history', 'نام': 'Name', 'شماره تماس / آدرس': 'Phone / address', 'فعال برای معاملات جدید': 'Active for new transactions',
  'ذخیرهٔ مشخصات': 'Save details', 'بستن سابقه': 'Close history', 'سابقه': 'History', 'جستجوی نام یا تماس': 'Search by name or contact', 'تماس': 'Contact', 'عملیات': 'Actions',
  'نام را وارد کنید.': 'Enter a name.', 'غیرفعال': 'Inactive', 'قابل پرداخت': 'Payable', 'قابل دریافت': 'Receivable',
  'مجموع خرید': 'Total purchases', 'مجموع فروش و اجرت': 'Total sales and service', 'مجموع فروش': 'Total sales', 'خرید برنج': 'Rice purchases', 'اجرت خدمات': 'Service charges',
  'پرداخت نقدی': 'Cash paid', 'پرداخت با برنج': 'Rice paid', 'وزن خریداری‌شده': 'Purchased weight', 'تحویل‌شده': 'Delivered', 'منتظر تحویل': 'Awaiting delivery',
  'مجموع موجودی خام': 'Total raw inventory', 'موجودی فیزیکی پروسس‌شده': 'Processed physical inventory', 'موجودی قابل فروش': 'Available inventory', 'برنج مشتری در گدام': 'Customer rice in storage',
  'مجموع خرید مواد خام': 'Total raw material purchases', 'مجموع فروش برنج': 'Total rice sales', 'اجرت پروسس امانتی': 'Contract processing charges', 'نقد دریافتی از مشتریان': 'Cash received from customers', 'قابل دریافت از مشتریان': 'Receivable from customers', 'نقد پرداختی به تأمین‌کنندگان': 'Cash paid to suppliers', 'قابل پرداخت به تأمین‌کنندگان': 'Payable to suppliers', 'مجموع مصارف': 'Total expenses', 'اجرت تسویه‌شده با برنج': 'Service charges settled with rice',
  'آمار پروسس کارخانه': 'Factory processing statistics', 'دسته‌های پروسس': 'Processing batches', 'وزن ورودی': 'Input weight', 'محصول تولیدشده': 'Produced product', 'ضایعات': 'Waste', 'آمار پروسس امانتی': 'Contract processing statistics', 'دسته‌های امانتی': 'Contract batches', 'ورودی مشتریان': 'Customer input', 'خروجی مشتریان': 'Customer output', 'ضایعات امانتی': 'Contract waste', 'موجودی هر نوع برنج خام': 'Inventory by raw rice type', 'موجودی هر محصول': 'Inventory by product', 'مصارف به تفکیک دسته': 'Expenses by category', 'آخرین معاملات': 'Recent transactions', 'شماره': 'Number', 'تاریخ': 'Date', 'نوع سند': 'Record type', 'شخص / محصول': 'Party / product', 'مبلغ / وزن': 'Amount / weight',
  'موجودی محاسبه‌شده از اسناد': 'Inventory calculated from records', 'مجموع برنج خام': 'Total raw rice', 'برنج پروسس‌شده در گدام': 'Processed rice in storage', 'برنج قابل فروش کارخانه': 'Factory rice available for sale', 'برنج مشتریان منتظر تحویل': 'Customer rice awaiting delivery', 'برنج خام': 'Raw rice', 'برنج پروسس‌شده': 'Processed rice', 'جستجوی محصول': 'Search products', 'موجودی فیزیکی = برنج قابل فروش کارخانه + برنج فروخته‌شدهٔ منتظر تحویل. موجودی از اسناد محاسبه می‌شود و دستی قابل تغییر نیست.': 'Physical inventory = factory rice available for sale + sold rice awaiting delivery. Inventory is calculated from records and cannot be changed manually.',
  'نوع برنج خام': 'Raw rice type', 'موجودی': 'Inventory', 'ارزش موجودی': 'Inventory value', 'میانگین قیمت فی کیلو': 'Average price per kg', 'محصول': 'Product', 'تولید کارخانه': 'Factory production', 'اجرت دریافتی با برنج': 'Service received in rice', 'فروخته‌شده': 'Sold', 'متعلق به مشتری در گدام': 'Customer-owned in storage', 'قابل فروش': 'Available for sale', 'موجودی فیزیکی': 'Physical inventory',
  'هزینه‌های پرداخت‌شدهٔ کارخانه': 'Factory expenses paid', 'مجموع ترانسپورت شامل مصارف ثبت‌شده همراه خرید است. مصارف پروسس از دسته‌های پروسس محاسبه می‌شوند؛ این موارد را دوباره ثبت نکنید.': 'Transport totals include expenses recorded with purchases. Processing expenses are calculated from processing batches; do not record them again.', 'اسناد مصارف مستقل': 'Independent expense records',
  'فروش، دریافت پول و خروج از گدام': 'Sales, payments, and stock release', 'با ثبت فروش، مالکیت برنج به مشتری انتقال می‌یابد و دیگر قابل فروش نیست. موجودی فیزیکی تنها هنگام ثبت تحویل کم می‌شود.': 'When a sale is recorded, ownership transfers to the customer and the rice is no longer available for sale. Physical inventory decreases only when delivery is recorded.', 'فروش‌ها و تحویل باقی‌مانده': 'Sales and remaining deliveries', 'سابقهٔ تحویل‌ها': 'Delivery history',
  'برنج متعلق به مشتری': 'Customer-owned rice', 'تبدیل مواد اولیه به محصول': 'Turning raw materials into products', 'پروسس امانتی': 'Contract processing', 'پروسس برنج': 'Rice processing',
  'ثبت خرید برنج خام': 'Record raw rice purchase', 'ثبت پروسس برنج کارخانه': 'Record factory rice processing', 'ثبت پروسس امانتی تکمیل‌شده': 'Record completed contract processing', 'ثبت مصرف': 'Record expense', 'ثبت فروش': 'Record sale', 'ثبت پروسس': 'Record processing',
  'بهای خرید': 'Purchase price', 'مصارف جداگانه': 'Additional expenses', 'قیمت تمام‌شده': 'Landed cost', 'قیمت واقعی فی کیلو': 'Actual price per kg', 'باقی‌حساب تأمین‌کننده': 'Supplier balance', 'باقی‌حساب': 'Balance', 'باقی در گدام برای مشتری': 'Customer rice remaining in storage', 'مجموع خروجی': 'Total output', 'هزینهٔ مواد خام': 'Raw material cost', 'مصرف پروسس فی کیلو ورودی': 'Processing cost per input kg', 'قیمت تمام‌شدهٔ دسته': 'Batch cost', 'قیمت فی کیلو خروجی': 'Cost per output kg', 'ارزش برنج دریافتی': 'Value of received rice', 'باقی‌حساب اجرت': 'Service charge balance',
  'ترانسپورت و مصارف اضافی جداگانه پرداخت می‌شوند. این مبلغ به قیمت موجودی افزوده می‌شود، نه به بدهی تأمین‌کننده. دوباره در بخش مصارف ثبت نکنید.': 'Transport and additional expenses are paid separately. This amount is added to inventory cost, not the supplier balance. Do not record it again as an expense.', 'این فورم را پس از تکمیل پروسس و بازگرداندن برنج ثبت کنید. فقط سهم اجرت وارد موجودی کارخانه می‌شود؛ باقی خروجی به صاحب برنج برگردانده می‌شود.': 'Submit this form after processing is complete and the rice is returned. Only the service share enters factory inventory; the remaining output goes back to the owner.', 'تأمین‌کننده *': 'Supplier *', 'مشتری / صاحب برنج *': 'Customer / rice owner *', 'نوع برنج خام *': 'Raw rice type *', 'قابل فروش:': 'Available:', 'وزن (کیلوگرام) *': 'Weight (kg) *', 'قیمت فی کیلو (افغانی) *': 'Price per kg (AFN) *', 'مصارف اضافی / ترانسپورت (افغانی)': 'Additional expenses / transport (AFN)', 'وزن ورودی خام (کیلوگرام) *': 'Raw input weight (kg) *', 'مصارف پرداخت‌شدهٔ پروسس (افغانی)': 'Processing expenses paid (AFN)', 'اجرت پروسس (افغانی) *': 'Processing charge (AFN) *', 'پرداخت نقدی به تأمین‌کننده (افغانی)': 'Cash paid to supplier (AFN)', 'دریافت نقدی از مشتری (افغانی)': 'Cash received from customer (AFN)', 'تحویل فعلی (کیلوگرام)': 'Current delivery (kg)', 'اگر برنج در گدام می‌ماند، صفر وارد کنید.': 'Enter zero if the rice remains in storage.', 'شرح مصرف *': 'Expense description *', 'دستهٔ مصرف *': 'Expense category *', 'مبلغ پرداخت‌شده (افغانی) *': 'Amount paid (AFN) *', 'شخص مسئول': 'Responsible person', 'تاریخ (میلادی) *': 'Date (Gregorian) *', 'یادداشت': 'Notes', 'کیفیت': 'Quality', 'خروجی (کیلوگرام)': 'Output (kg)', 'سهم کارخانه (کیلوگرام)': 'Factory share (kg)', 'قیمت توافقی فی کیلو': 'Agreed price per kg', 'برگشت به صاحب': 'Returned to owner', 'قیمت نمایش‌داده‌شده تخمینی است؛ قیمت نهایی با میانگین وزنی موجودی در لحظهٔ ثبت محاسبه می‌شود.': 'The displayed price is an estimate; the final price is calculated from the weighted inventory average when saved.', 'ثبت نهایی': 'Save record', 'سند نهایی مستقیماً ویرایش یا حذف نمی‌شود. برای اصلاح، سند را با ذکر دلیل باطل و دوباره ثبت کنید.': 'Final records cannot be edited or deleted directly. To correct one, void it with a reason and record it again.',
  'سابقهٔ معاملات': 'Transaction history', 'دلیل ابطال *': 'Void reason *', 'اثر سند برگشت داده می‌شود و سابقهٔ آن باقی می‌ماند. ابتدا پرداخت‌ها و تحویل‌های وابسته را باطل کنید.': 'The record will be reversed and its history retained. Void related payments and deliveries first.', 'مبلغ (افغانی)': 'Amount (AFN)', 'وزن (کیلوگرام)': 'Weight (kg)', 'باقی‌مانده:': 'Remaining:', 'در حال دریافت اسناد…': 'Loading records…', 'نمایش اسناد باطل‌شده': 'Show voided records', 'جستجو در اسناد': 'Search records', 'نام، محصول یا شمارهٔ سند': 'Name, product, or record number', 'از تاریخ (میلادی)': 'From date (Gregorian)', 'تا تاریخ (میلادی)': 'To date (Gregorian)', 'دستهٔ مصرف': 'Expense category', 'همهٔ دسته‌ها': 'All categories', 'نوع': 'Type', 'باطل': 'Voided', 'مبلغ سند': 'Record amount', 'مصرف پروسس فی کیلو ورودی': 'Processing cost per input kg', 'قیمت مواد خام': 'Raw material cost', 'مصارف پروسس': 'Processing expenses', 'مجموع قیمت دسته': 'Total batch cost', 'اجرت تسویه‌شده با برنج': 'Service charge settled with rice', 'تحویل‌شده': 'Delivered', 'منتظر تحویل': 'Awaiting delivery', 'وضعیت تحویل': 'Delivery status', 'تکمیل': 'Complete', 'قسمی': 'Partial', 'تحویل نشده': 'Not delivered', 'شرح': 'Description', 'مسئول': 'Responsible', 'بابت': 'For', 'شمارهٔ سند مربوط': 'Related record number', 'یادداشت:': 'Note:', 'باطل‌شده:': 'Voided:', 'سند': 'records', 'مجموع اسناد فعال:': 'Active records total:', 'صفحهٔ': 'Page', 'پرداخت و تحویل هر فاکتور را از همان ردیف ثبت کنید. پرداخت‌ها و تحویل‌ها نیز برای اصلاح در این سابقه دیده می‌شوند.': 'Record payment and delivery for each invoice from its row. Payments and deliveries also appear here for correction.',
  'اصلی': 'Premium', 'متوسط': 'Medium', 'متوسط کمزوری': 'Lower medium', 'میدگی': 'Broken', 'با موفقیت ثبت شد.': 'Saved successfully.', 'تاریخ معتبر را وارد کنید.': 'Enter a valid date.', 'تأمین‌کننده یا مشتری را انتخاب کنید.': 'Select a supplier or customer.', 'نوع برنج خام را انتخاب کنید.': 'Select a raw rice type.', 'محصول را انتخاب کنید.': 'Select a product.', 'قیمت فی کیلو را وارد کنید.': 'Enter the price per kg.', 'اجرت پروسس را وارد کنید.': 'Enter the processing charge.', 'همهٔ وزن‌ها و مبالغ باید اعداد معتبر و غیرمنفی باشند.': 'All weights and amounts must be valid non-negative numbers.', 'وزن تا سه رقم اعشار، قیمت فی کیلو تا چهار رقم و مبلغ تا دو رقم اعشار قابل ثبت است.': 'Weights support up to three decimals, prices per kg up to four, and amounts up to two.', 'وزن باید بیشتر از صفر باشد.': 'Weight must be greater than zero.', 'وزن ورودی باید بیشتر از صفر باشد.': 'Input weight must be greater than zero.', 'مقادیر خروجی معتبر نیستند.': 'Output values are invalid.', 'وزن خروجی تا سه و قیمت توافقی تا چهار رقم اعشار قابل ثبت است.': 'Output weights support up to three decimals and agreed prices up to four.', 'برنج دریافتی کارخانه نمی‌تواند بیشتر از خروجی باشد.': 'The factory share cannot exceed the output.', 'برای برنج دریافتی، قیمت توافقی فی کیلو را وارد کنید.': 'Enter an agreed price per kg for the factory share.', 'مجموع پرداخت نقدی و برنج از مبلغ سند بیشتر است.': 'Cash and rice payments exceed the record amount.', 'خروجی باید مثبت و کمتر یا مساوی ورودی باشد.': 'Output must be positive and no greater than input.', 'موجودی برنج خام کافی نیست.': 'There is not enough raw rice inventory.', 'موجودی قابل فروش کافی نیست.': 'There is not enough available inventory.', 'تحویل نمی‌تواند بیشتر از وزن فروش باشد.': 'Delivery cannot exceed the sale weight.', 'شرح، دسته و مبلغ مثبت مصرف را وارد کنید.': 'Enter an expense description, category, and positive amount.', 'دلیل ابطال را بنویسید.': 'Enter a void reason.', 'تاریخ و مقدار مثبت معتبر را وارد کنید.': 'Enter a valid date and positive amount.', 'پرداخت از باقی‌حساب بیشتر است.': 'Payment exceeds the remaining balance.', 'وزن تحویل از باقی‌مانده بیشتر است.': 'Delivery exceeds the remaining weight.', 'ابطال سند': 'Void record', 'ثبت پرداخت نقدی': 'Record cash payment', 'ثبت تحویل برنج': 'Record rice delivery', 'بستن جزئیات': 'Close details',
  'راه‌اندازی دیتابیس تکمیل نشده است. مدیر سیستم باید فایل‌های مهاجرت را اجرا کند.': 'Database setup is incomplete. An administrator must run the migrations.', 'مقادیر واردشده معتبر نیستند؛ وزن، مبلغ و خانه‌های ضروری را بررسی کنید.': 'The entered values are invalid. Check weights, amounts, and required fields.', 'این مورد قبلاً ثبت شده است؛ اطلاعات تکراری را بررسی کنید.': 'This item already exists. Check for duplicate information.', 'شخص، محصول یا سند انتخاب‌شده معتبر نیست. فهرست را تازه کنید.': 'The selected party, product, or record is invalid. Refresh the list.', 'اطلاعات هم‌زمان تغییر کرده است. لطفاً دوباره کوشش کنید.': 'The data changed concurrently. Please try again.', 'اجازهٔ این عملیات را ندارید. با مدیر سیستم تماس بگیرید.': 'You do not have permission for this operation. Contact your administrator.', 'ارتباط با سیستم برقرار نشد. اتصال انترنت را بررسی کرده و دوباره کوشش کنید.': 'Could not connect to the system. Check your internet connection and try again.'
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => localStorage.getItem(STORAGE_KEY) || defaultLanguage);
  const isDari = language === 'fa-AF';
  const direction = isDari ? 'rtl' : 'ltr';
  const setLanguage = next => setLanguageState(next === 'en' ? 'en' : defaultLanguage);
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    document.documentElement.dir = 'ltr';
  }, [language]);
  const value = useMemo(() => ({ language, isDari, direction, setLanguage, t: (key, vars = {}) => {
    let value = isDari ? key : (english[key] || key);
    Object.entries(vars).forEach(([name, replacement]) => { value = value.replace(`{${name}}`, replacement); });
    return value;
  }}), [language, isDari, direction]);
  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  return useContext(LanguageContext);
}

