import { useEffect, useRef, useState } from 'react';
import PageHeading from '../components/PageHeading.jsx';
import DateInput from '../components/DateInput.jsx';
import Alert from '../components/Alert.jsx';
import { Card, Input, Notice, Stat, Table, buttonClass, secondaryClass } from '../components/Fields.jsx';
import { deleteEmployee, fetchSalaryOverview, fetchSalarySnapshot, payEmployeeSalary, saveEmployee } from '../services/millApi.js';
import { dateLabel, errorMessage, money, normalizeDigits, number, numeric, today } from '../lib/format.js';
import { solarMonthNames, toSolarHijri } from '../lib/calendar.js';
import { useLanguage } from '../hooks/useLanguage.js';

const blankEmployee=()=>({name:'',father_name:'',contact:'',role:'',monthly_salary:'',start_date:today()});
export default function StaffSalariesPage(){
  const {t}=useLanguage();
  const currentMonth=toSolarHijri(today()).slice(0,7);
  const [month,setMonth]=useState(currentMonth); const [data,setData]=useState({employees:[],payments:[],salary_total:0,paid_total:0,remaining_total:0});
  const [overview,setOverview]=useState({months:[],overdue_items:[],overdue_total:0});
  const [form,setForm]=useState(blankEmployee); const [showForm,setShowForm]=useState(false); const [paying,setPaying]=useState(null); const [payment,setPayment]=useState({amount:'',date:today(),notes:''});
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false); const [reload,setReload]=useState(0); const request=useRef(null);
  useEffect(()=>{let active=true;fetchSalarySnapshot(month).then(value=>{if(active){setData(value);setError('');}}).catch(err=>{if(active)setError(errorMessage(err));});return()=>{active=false;};},[month,reload]);
  useEffect(()=>{let active=true;fetchSalaryOverview(Number(month.slice(0,4)),today()).then(value=>{if(active)setOverview(value);}).catch(err=>{if(active)setError(errorMessage(err));});return()=>{active=false;};},[month,reload]);
  const monthName=value=>{const index=Number(value.slice(5,7))-1;return `${t(solarMonthNames[index])} ${number(value.slice(0,4),0)}`;};
  const statusLabel=status=>({paid:'Paid in full',partial:'Partly paid',unpaid:'Not paid',overdue:'Overdue',none:'No staff'}[status]||status);
  const statusClass=status=>({paid:'bg-emerald-100 text-emerald-800',partial:'bg-amber-100 text-amber-800',unpaid:'bg-stone-100 text-stone-600',overdue:'bg-red-100 text-red-800',none:'bg-stone-100 text-stone-500'}[status]);
  async function save(e){e.preventDefault();if(!form.name.trim()||numeric(form.monthly_salary)<=0){setError('Enter an employee name and positive monthly salary.');return;}setBusy(true);setError('');request.current ||= crypto.randomUUID();try{await saveEmployee(form,request.current);request.current=null;setForm(blankEmployee());setShowForm(false);setSuccess('Employee saved successfully.');setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  async function remove(row){if(!window.confirm(t('Delete {name}? Their salary payment history will be preserved.',{name:row.name})))return;setBusy(true);try{await deleteEmployee(row.id);setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  function startPayment(row){setPaying(row.id);setPayment({amount:String(row.remaining),date:today(),notes:''});setError('');setSuccess('');}
  async function pay(e){e.preventDefault();const employee=data.employees.find(row=>row.id===paying);if(numeric(payment.amount)<=0||numeric(payment.amount)>Number(employee.remaining)){setError('Salary payment must be positive and no greater than the remaining salary.');return;}setBusy(true);request.current ||= crypto.randomUUID();try{await payEmployeeSalary({...payment,employee_id:paying,solar_month:month},request.current);request.current=null;setPaying(null);setSuccess('Salary payment saved successfully.');setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  return <div className="space-y-6"><PageHeading eyebrow="Employee records and monthly salary payments" title="Staff and salaries" />
    {!!overview.overdue_items?.length&&<section className="rounded-xl border border-red-200 bg-red-50 p-5" role="alert"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-semibold text-red-900">{t('Salary payments are overdue')}</h2><p className="mt-1 text-sm leading-6 text-red-800">{t('{count} salary payments from past months still have a balance.',{count:number(overview.overdue_items.length,0)})}</p></div><strong className="text-red-900">{money(overview.overdue_total)}</strong></div><div className="mt-4 flex flex-wrap gap-2">{overview.overdue_items.map(item=><button key={`${item.employee_id}-${item.month}`} onClick={()=>setMonth(item.month)} className="rounded-lg border border-red-200 bg-white px-3 py-2 text-xs text-red-800 hover:bg-red-100">{item.employee_name} · {monthName(item.month)} · {money(item.remaining)}</button>)}</div></section>}
    <Card title="Salary month"><div className="flex items-center justify-between gap-3"><button className={secondaryClass} aria-label={t('Previous year')} onClick={()=>setMonth(`${Number(month.slice(0,4))-1}-${month.slice(5)}`)}>‹</button><strong>{number(month.slice(0,4),0)}</strong><button className={secondaryClass} aria-label={t('Next year')} onClick={()=>setMonth(`${Number(month.slice(0,4))+1}-${month.slice(5)}`)}>›</button></div><div className="mt-5 grid gap-2 sm:grid-cols-3 lg:grid-cols-4">{overview.months.map(item=><button key={item.month} onClick={()=>setMonth(item.month)} className={`rounded-lg border p-3 text-start transition ${month===item.month?'border-brand bg-brand text-white':'border-line bg-white hover:bg-surface'}`}><span className="flex items-center justify-between gap-2"><strong className="text-sm">{monthName(item.month)}</strong><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${month===item.month?'bg-white/20 text-white':statusClass(item.status)}`}>{t(statusLabel(item.status))}</span></span><span className={`mt-2 block text-xs ${month===item.month?'text-white/80':'text-stone-500'}`}>{item.employee_count?t('{paid} paid · {remaining} remaining',{paid:money(item.paid_total),remaining:money(item.remaining_total)}):t('No staff employed')}</span></button>)}</div></Card>
    <div className="grid gap-4 sm:grid-cols-3"><Stat label="Total salary expense" value={money(data.salary_total)} /><Stat label="Salaries paid" value={money(data.paid_total)} /><Stat label="Salaries remaining" value={money(data.remaining_total)} /></div>
    {!showForm&&<button className={buttonClass} onClick={()=>{setForm(blankEmployee());setShowForm(true);}}>{t('Add employee')}</button>}
    {showForm&&<Card title={form.id?'Edit employee':'Add employee'}><form onSubmit={save} noValidate><fieldset disabled={busy} className="grid items-end gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Input label="Employee name *" value={form.name} onChange={name=>setForm(v=>({...v,name}))} maxLength={160}/><Input label="Father name" value={form.father_name} onChange={father_name=>setForm(v=>({...v,father_name}))} maxLength={160}/><Input label="Phone / address" value={form.contact} onChange={contact=>setForm(v=>({...v,contact}))} maxLength={200}/><Input label="Job / role" value={form.role} onChange={role=>setForm(v=>({...v,role}))} maxLength={160}/><Input label="Monthly salary (AFN) *" inputMode="decimal" value={form.monthly_salary} onChange={monthly_salary=>setForm(v=>({...v,monthly_salary:normalizeDigits(monthly_salary)}))}/><DateInput label="Employment start date" value={form.start_date} onChange={start_date=>setForm(v=>({...v,start_date}))} required/>
      <div className="col-span-full"><Alert>{error}</Alert><button className={buttonClass}>{busy?t('Saving…'):t('Save details')}</button><button type="button" className={`${secondaryClass} ms-3`} onClick={()=>setShowForm(false)}>{t('Cancel')}</button></div>
    </fieldset></form></Card>}
    {paying&&<Card title="Record salary payment"><form onSubmit={pay} noValidate><fieldset disabled={busy} className="grid items-end gap-4 sm:grid-cols-3"><Input label="Amount (AFN) *" inputMode="decimal" value={payment.amount} onChange={amount=>setPayment(v=>({...v,amount:normalizeDigits(amount)}))}/><DateInput label="Payment date" value={payment.date} onChange={date=>setPayment(v=>({...v,date}))} required/><Input label="Notes" value={payment.notes} onChange={notes=>setPayment(v=>({...v,notes}))}/><div className="col-span-full"><Alert>{error}</Alert><button className={buttonClass}>{busy?t('Saving…'):t('Save payment')}</button><button type="button" className={`${secondaryClass} ms-3`} onClick={()=>setPaying(null)}>{t('Cancel')}</button></div></fieldset></form></Card>}
    <Alert>{error}</Alert><Notice>{success}</Notice><Card title="Employees and salary balances"><Table rows={data.employees} columns={[{key:'name',label:'Name'},{key:'father_name',label:'Father name'},{key:'role',label:'Job / role'},{key:'contact',label:'Contact'},{key:'monthly_salary',label:'Monthly salary',render:r=>money(r.monthly_salary)},{key:'paid',label:'Paid',render:r=>money(r.paid)},{key:'remaining',label:'Remaining',render:r=>money(r.remaining)},{key:'actions',label:'Actions',render:r=><div className="flex flex-wrap gap-2">{Number(r.remaining)>0&&<button className={buttonClass} onClick={()=>startPayment(r)}>{t('Pay salary')}</button>}<button className={secondaryClass} onClick={()=>{setForm({...r,monthly_salary:String(r.monthly_salary)});setShowForm(true);}}>{t('Edit')}</button>{r.active&&<button className={`${secondaryClass} text-red-700`} onClick={()=>remove(r)}>{t('Delete')}</button>}</div>}]} /></Card>
    <Card title="Salary payment history"><Table rows={data.payments || []} columns={[{key:'employee_name',label:'Employee name'},{key:'payment_date',label:'Payment date',render:r=>dateLabel(r.payment_date)},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'notes',label:'Notes'}]} /></Card>
  </div>;
}
