import { useEffect, useRef, useState } from 'react';
import PageHeading from '../components/PageHeading.jsx';
import DateInput from '../components/DateInput.jsx';
import Alert from '../components/Alert.jsx';
import { Card, Input, Notice, Stat, Table, buttonClass, secondaryClass } from '../components/Fields.jsx';
import { deleteEmployee, fetchSalarySnapshot, payEmployeeSalary, saveEmployee } from '../services/millApi.js';
import { dateLabel, errorMessage, money, normalizeDigits, numeric, today } from '../lib/format.js';
import { toSolarHijri } from '../lib/calendar.js';
import { useLanguage } from '../hooks/useLanguage.js';

const blankEmployee=()=>({name:'',father_name:'',contact:'',role:'',monthly_salary:'',start_date:today()});
export default function StaffSalariesPage(){
  const {t}=useLanguage();
  const [month,setMonth]=useState(toSolarHijri(today()).slice(0,7)); const [data,setData]=useState({employees:[],payments:[],salary_total:0,paid_total:0,remaining_total:0});
  const [form,setForm]=useState(blankEmployee); const [showForm,setShowForm]=useState(false); const [paying,setPaying]=useState(null); const [payment,setPayment]=useState({amount:'',date:today(),notes:''});
  const [error,setError]=useState(''); const [success,setSuccess]=useState(''); const [busy,setBusy]=useState(false); const [reload,setReload]=useState(0); const request=useRef(null);
  useEffect(()=>{let active=true;fetchSalarySnapshot(month).then(value=>{if(active){setData(value);setError('');}}).catch(err=>{if(active)setError(errorMessage(err));});return()=>{active=false;};},[month,reload]);
  async function save(e){e.preventDefault();if(!form.name.trim()||numeric(form.monthly_salary)<=0){setError('Enter an employee name and positive monthly salary.');return;}setBusy(true);setError('');request.current ||= crypto.randomUUID();try{await saveEmployee(form,request.current);request.current=null;setForm(blankEmployee());setShowForm(false);setSuccess('Employee saved successfully.');setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  async function remove(row){if(!window.confirm(t('Delete {name}? Their salary payment history will be preserved.',{name:row.name})))return;setBusy(true);try{await deleteEmployee(row.id);setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  function startPayment(row){setPaying(row.id);setPayment({amount:String(row.remaining),date:today(),notes:''});setError('');setSuccess('');}
  async function pay(e){e.preventDefault();const employee=data.employees.find(row=>row.id===paying);if(numeric(payment.amount)<=0||numeric(payment.amount)>Number(employee.remaining)){setError('Salary payment must be positive and no greater than the remaining salary.');return;}setBusy(true);request.current ||= crypto.randomUUID();try{await payEmployeeSalary({...payment,employee_id:paying,solar_month:month},request.current);request.current=null;setPaying(null);setSuccess('Salary payment saved successfully.');setReload(v=>v+1);}catch(err){setError(errorMessage(err));}finally{setBusy(false);}}
  return <div className="space-y-6"><PageHeading eyebrow="Employee records and monthly salary payments" title="Staff and salaries" />
    <Card title="Salary month"><div className="max-w-sm"><Input label="Solar Hijri month *" hint="Format: YYYY-MM" value={month} onChange={value=>setMonth(normalizeDigits(value))} maxLength={7} /></div></Card>
    <div className="grid gap-4 sm:grid-cols-3"><Stat label="Total salary expense" value={money(data.salary_total)} /><Stat label="Salaries paid" value={money(data.paid_total)} /><Stat label="Salaries remaining" value={money(data.remaining_total)} /></div>
    {!showForm&&<button className={buttonClass} onClick={()=>{setForm(blankEmployee());setShowForm(true);}}>{t('Add employee')}</button>}
    {showForm&&<Card title={form.id?'Edit employee':'Add employee'}><form onSubmit={save} noValidate><fieldset disabled={busy} className="grid items-end gap-4 sm:grid-cols-2 lg:grid-cols-3">
      <Input label="Employee name *" value={form.name} onChange={name=>setForm(v=>({...v,name}))} maxLength={160}/><Input label="Father name" value={form.father_name} onChange={father_name=>setForm(v=>({...v,father_name}))} maxLength={160}/><Input label="Phone / address" value={form.contact} onChange={contact=>setForm(v=>({...v,contact}))} maxLength={200}/><Input label="Job / role" value={form.role} onChange={role=>setForm(v=>({...v,role}))} maxLength={160}/><Input label="Monthly salary (AFN) *" inputMode="decimal" value={form.monthly_salary} onChange={monthly_salary=>setForm(v=>({...v,monthly_salary:normalizeDigits(monthly_salary)}))}/><DateInput label="Employment start date" value={form.start_date} onChange={start_date=>setForm(v=>({...v,start_date}))} required/>
      <div className="col-span-full"><Alert>{error}</Alert><button className={buttonClass}>{busy?t('Saving…'):t('Save details')}</button><button type="button" className={`${secondaryClass} ms-3`} onClick={()=>setShowForm(false)}>{t('Cancel')}</button></div>
    </fieldset></form></Card>}
    {paying&&<Card title="Record salary payment"><form onSubmit={pay} noValidate><fieldset disabled={busy} className="grid items-end gap-4 sm:grid-cols-3"><Input label="Amount (AFN) *" inputMode="decimal" value={payment.amount} onChange={amount=>setPayment(v=>({...v,amount:normalizeDigits(amount)}))}/><DateInput label="Payment date" value={payment.date} onChange={date=>setPayment(v=>({...v,date}))} required/><Input label="Notes" value={payment.notes} onChange={notes=>setPayment(v=>({...v,notes}))}/><div className="col-span-full"><Alert>{error}</Alert><button className={buttonClass}>{busy?t('Saving…'):t('Save payment')}</button><button type="button" className={`${secondaryClass} ms-3`} onClick={()=>setPaying(null)}>{t('Cancel')}</button></div></fieldset></form></Card>}
    <Alert>{error}</Alert><Notice>{success}</Notice><Card title="Employees and salary balances"><Table rows={data.employees} columns={[{key:'name',label:'Name'},{key:'father_name',label:'Father name'},{key:'role',label:'Job / role'},{key:'contact',label:'Contact'},{key:'monthly_salary',label:'Monthly salary',render:r=>money(r.monthly_salary)},{key:'paid',label:'Paid',render:r=>money(r.paid)},{key:'remaining',label:'Remaining',render:r=>money(r.remaining)},{key:'actions',label:'Actions',render:r=><div className="flex flex-wrap gap-2">{Number(r.remaining)>0&&<button className={buttonClass} onClick={()=>startPayment(r)}>{t('Pay salary')}</button>}<button className={secondaryClass} onClick={()=>{setForm({...r,monthly_salary:String(r.monthly_salary)});setShowForm(true);}}>{t('Edit')}</button>{r.active&&<button className={`${secondaryClass} text-red-700`} onClick={()=>remove(r)}>{t('Delete')}</button>}</div>}]} /></Card>
    <Card title="Salary payment history"><Table rows={data.payments || []} columns={[{key:'employee_name',label:'Employee name'},{key:'payment_date',label:'Payment date',render:r=>dateLabel(r.payment_date)},{key:'amount',label:'Amount',render:r=>money(r.amount)},{key:'notes',label:'Notes'}]} /></Card>
  </div>;
}
